### ISSUE TITLE
How to perform Spectral Pretrain with resnet18 backbone?

### ISSUE THREAD

**Issue by Iranb** [deeplearning-wisc/sorl#2]
How to pretrain Resnet 18 model with **Spectral Loss** on CIFAR100 dataset as described in the paper?  

Can I directly utilize the '[spectral.py](https://github.com/deeplearning-wisc/sorl/blob/master/models/spectral.py)' from the codebase to conduct the spectral pretraining process? What are the parameters used during the pretraining phase?

**Comment by sunyiyou** [comment]
Yes, you can use spectral.py to do this pretraining. Our code is mainly derived from https://github.com/jhaochenz/spectral_contrastive_learning. Following their pretraining setting should work.
